name: Cache Demo Workflow

on:
  workflow_dispatch:   # lets you run it manually

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-055f219

      - name: prime-cache-055f219
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
